# name: Version

# on:
#   push:
#     branches:
#       - main

# jobs:
#   version:
#     name: Version
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v3
#         with:
#           # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
#           fetch-depth: 0

#       - name: Setup Node
#         uses: actions/setup-node@v3
#         with:
#           node-version: 20
#           registry-url: https://registry.npmjs.org
#           cache: yarn

#       - name: Install dependencies
#         run: yarn install --frozen-lockfile

#       - name: Create Release Pull Request or Publish
#         uses: changesets/action@v1
#         id: changesets
#         with:
#           version: yarn version
#           publish: yarn release
#         env:
#           GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
#     outputs:
#       ref: ${{ github.ref }}
#       published: ${{ steps.changesets.outputs.published }}

#   deploy-to-static-file-host:
#     name: Deploy to Static File Host
#     uses: ./.github/workflows/deploy-to-static-file-host.yml
#     needs: version
#     with:
#       ref: ${{ needs.version.outputs.ref }}
#     if: ${{ needs.version.outputs.published }}
